### PR TITLE
new policy added

### PR DESCRIPTION
**Pull request by eliranMoz**

### CODE REVIEW

**Review by aviat-ct — CHANGES_REQUESTED** [review]
1) please add readme
2) directory name missing an 'e'

**Review by eliranMoz — COMMENTED** [review]
readme added and fix folder name

**Review by eliranMoz — COMMENTED** [review]
new formatting to readme file

**Comment by haimdagan8** [comment]
Looks fine.
Great job !

**Review by aviat-ct — APPROVED** [review]

**Comment by aviat-ct** [comment]
@eliranMoz - made some minor changes to the readme file

**Pull request merged**
